Imtahan/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Imtahan.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles ="Admin")]
	public class DashboardController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Imtahan/Areas/Admin/Controllers/TeamController.cs
using Bussiness.Abstracts;
using Bussiness.Exceptions;
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

namespace Imtahan.Areas.Admin.Controllers
{
    [Area("Admin")]
	[Authorize(Roles = "Admin")]

	public class TeamController : Controller
    {
        ITeamService _teamService;

        public TeamController(ITeamService teamService)
        {
            _teamService = teamService;
        }

        public IActionResult Index()
        {
            var teams= _teamService.GetAllTeams();
            return View(teams);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Team team)
        {
            try
            {
                _teamService.Create(team);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch(NotNullException ex)
            {
                ModelState.AddModelError(ex.Property,ex.Message);
                return View();
            }
            catch (FileContentTypeException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
                return View();
            }
            catch (FileSizeException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
                return View();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            try
            {
                _teamService.Delete(id);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var updateTeam = _teamService.GetTeam();
            if(updateTeam == null)
            {
                return NotFound();
            }
            return View(updateTeam);
        }
        [HttpPost]
        public IActionResult Update(Team team)
        {
            try
            {
                _teamService.Update(team.Id,team);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch (FileContentTypeException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
                return View();
            }
            catch (FileSizeException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
                return View();
            }
            return RedirectToAction("Index");

        }
    }
}

Imtahan/Controllers/AccountController.cs
using Core.Models;
using Imtahan.DTOs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Imtahan.Controllers
{
	public class AccountController : Controller
	{
		UserManager<User> _userManager;
        SignInManager<User> _signInManager;
        RoleManager<IdentityRole> _roleManager;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }


        public IActionResult Register()
		{
			return View();
		}
		[HttpPost]
		public async  Task<IActionResult> Register(RegisterDto registerDto)
		{
			if(!ModelState.IsValid)
			{
				return View();
			}
			User user= new User()
			{
				Name = registerDto.Name,
				Surname = registerDto.Surname,
				Email = registerDto.Email,
				UserName = registerDto.UserName,
			};
			var result= await _userManager.CreateAsync(user,registerDto.Password);
			if(!result.Succeeded)
			{
				foreach(var item in result.Errors)
				{
					ModelState.AddModelError("", item.Description);
					return View();
				}
			}
			await _signInManager.SignInAsync(user, false);
			await _userManager.AddToRoleAsync(user, "Admin");
			return RedirectToAction("Index","Home");
		}
		public IActionResult Login()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Login(LoginDto loginDto)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}
			var user = await _userManager.FindByNameAsync(loginDto.UserNameOrEmail);
			if (user == null)
			{
				user = await _userManager.FindByEmailAsync(loginDto.UserNameOrEmail);
				if (user == null)
				{
					ModelState.AddModelError("", "Username ve ya password yanlisdir!");
					return View();
				}
				
			}
			var result= await _signInManager.CheckPasswordSignInAsync(user,loginDto.Password,true);
			if(result.IsLockedOut)
			{
				ModelState.AddModelError("", "Birazdan yeniden cehd edin!!!!");
				return View();
			}
			if(!result.Succeeded)
			{
                ModelState.AddModelError("", "Username ve ya password yanlisdir!");
				return View();
            }
			await _signInManager.SignInAsync(user, loginDto.IsRemember);
			return RedirectToAction("Index", "Home");
		}
		public async Task<IActionResult> LogOut()
		{
			await _signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}
		public async Task<IActionResult> CreateRole()
		{
			IdentityRole role=new IdentityRole("Admin");
			IdentityRole role1 = new IdentityRole("Member");
			await _roleManager.CreateAsync(role);
			await _roleManager.CreateAsync(role1);

			return Ok();
		}
	}
}

Imtahan/Controllers/HomeController.cs
using Bussiness.Abstracts;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Imtahan.Controllers
{
    public class HomeController : Controller
    {

        ITeamService _service;

        public HomeController(ITeamService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            var teams= _service.GetAllTeams();
            return View(teams);
        }

   
    }
}

Imtahan/Areas/Admin/Views/Team/Create.cshtml
@using Core.Models
@model Team
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" >
            <span asp-validation-for="Name" style="color:red"></span>
        </div>
        <div class="form-group">
            <label asp-for="Position">Position</label>
            <input asp-for="Position" class="form-control">
            <span asp-validation-for="Position" style="color:red"></span>
        </div>
        <div class="form-group">
            <label asp-for="PhotoFile">PhotoFile</label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:red"></span>
        </div>
       
       
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Imtahan/Areas/Admin/Views/Team/Index.cshtml
@using Core.Models
@model List<Team>
@{
    int count = 0;
}
<div class="container">
    <h1>
        Teams
        <a class="btn btn-primary" asp-action="Create">Create</a>
    </h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Position</th>
                <th scope="col">Image</th>

            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                count++;
                <tr>
                    
                    <td>@count</td>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Position</td>
                   <td>
                       <img  src="~/Upload/Team/@item.ImgUrl" height="100" width="100"/>
                   </td>

                   <td>
                       <a class="btn btn-warning" asp-action="Update" asp-controller="Team" asp-route-id="@item.Id">Update</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Team" asp-route-id="@item.Id">Delete</a>

                   </td>




                </tr>
            }

        </tbody>
    </table>
</div>

Imtahan/Areas/Admin/Views/Team/Update.cshtml
@using Core.Models
@model Team
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>
        <div class="form-group">
            <label asp-for="Position">Position</label>
            <input asp-for="Position" class="form-control">
            <span asp-validation-for="Position" style="color:red"></span>
        </div>
        <div class="form-group">
            <label asp-for="PhotoFile">PhotoFile</label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:red"></span>
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Imtahan/Views/Home/Index.cshtml
@using Core.Models
@model List<Team>
<!-- banner -->
<div class="banner">
	<div class="container">
		<!-- heading -->
		<h2>I'm Banner Heading for This Page</h2>
		<!-- paragraph -->
		<p>It is our belief that in order to be most efficient it requires adaptive technology and software our customers can focus on their core business.</p>
	</div>
</div>
<!-- banner end -->
<!-- after banner -->
<div class="after-banner">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-sm-4">
				<!-- after banner item -->
				<div class="ab-item">
					<!-- heading -->
					<h3>Focus on Systems</h3>
					<!-- paragraph -->
					<p>While our prices are competitive, it's the value that's unmatched.</p>
					<br>
					<a href="#">Read More</a>
				</div>
			</div>
			<div class="col-md-4 col-sm-4">
				<!-- after banner item -->
				<div class="ab-item">
					<!-- heading -->
					<h3>Plan of Action</h3>
					<!-- paragraph -->
					<p>While our prices are competitive, it's the value that's unmatched.</p>
					<br>
					<a href="#">Read More</a>
				</div>
			</div>
			<div class="col-md-4 col-sm-4">
				<!-- after banner item -->
				<div class="ab-item">
					<!-- heading -->
					<h3>Quality Compliance</h3>
					<!-- paragraph -->
					<p>While our prices are competitive, it's the value that's unmatched.</p>
					<br>
					<a href="#">Read More</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- after banner end-->
<!-- events -->
<div class="event" id="event">
	<div class="container">
		<div class="default-heading">
			<!-- heading -->
			<h2>Upcoming events</h2>
		</div>
		<div class="row">
			<div class="col-md-4 col-sm-4">
				<!-- event item -->
				<div class="event-item">
					<!-- image -->
					<img class="img-responsive" src="~/theme/img/event/1.jpg" alt="Events" />
					<!-- heading -->
					<h4><a href="#">Rihanna, Eminem on stage</a></h4>
					<!-- sub text -->
					<span class="sub-text">Integrating technology and software solutions.</span>
					<!-- paragraph -->
					<p>It is our belief that in order to be most efficient it requires adaptive technology and software solutions.</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4">
				<!-- event item -->
				<div class="event-item">
					<!-- image -->
					<img class="img-responsive" src="~/theme/img/event/2.jpg" alt="Events" />
					<!-- heading -->
					<h4><a href="#">Dr. Dre on stage live</a></h4>
					<!-- sub text -->
					<span class="sub-text">Integrating technology and software solutions.</span>
					<!-- paragraph -->
					<p>It is our belief that in order to be most efficient it requires adaptive technology and software solutions.</p>
				</div>
			</div>
			<div class="col-md-4 col-sm-4">
				<!-- event item -->
				<div class="event-item">
					<!-- image -->
					<img class="img-responsive" src="~/theme/img/event/3.jpg" alt="Events" />
					<!-- heading -->
					<h4><a href="#">Macaroons live Party</a></h4>
					<!-- sub text -->
					<span class="sub-text">Integrating technology and software solutions.</span>
					<!-- paragraph -->
					<p>It is our belief that in order to be most efficient it requires adaptive technology and software solutions.</p>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- events end -->
<!-- blog -->
<div class="blog" id="blog">
	<div class="container">
		<div class="default-heading">
			<!-- heading -->
			<h2>Latest Blogs</h2>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-6">
				<!-- blog entry -->
				<div class="entry">
					<!-- blog entry image -->
					<img class="img-responsive" src="~/theme/img/blog/1.jpg" alt="Blog" />
					<!-- heading / blog post title -->
					<h3><a href="#">Communicating with you every step of the way</a></h3>
					<!-- blog information -->
					<span class="meta">
						July 02, 2014 | Tag: Technology | By: David John
					</span>
					<!-- paragraph -->
					<p>We combine continuing education and constant monitoring us with your project details if you are interested to ge of industry trends and innovations to provide the right IT solution at the right time. Contact us with your project details if you are interested to get our Web Solution or Software Development Services.</p>
				</div>
			</div>
			<div class="col-md-6 col-sm-6">
				<!-- blog entry -->
				<div class="entry">
					<!-- blog entry image -->
					<img class="img-responsive" src="~/theme/img/blog/2.jpg" alt="Blog" />
					<!-- heading / blog post title -->
					<h3><a href="#">Communicating with you every step of the way</a></h3>
					<!-- blog information -->
					<span class="meta">
						July 02, 2014 | Tag: Technology | By: David John
					</span>
					<!-- paragraph -->
					<p>We combine continuing education and constant monitoring us with your project details if you are interested to ge of industry trends and innovations to provide the right IT solution at the right time. Contact us with your project details if you are interested to get our Web Solution or Software Development Services.</p>
				</div>
			</div>
		</div>
		<div class="text-center">
			<a href="#" class="btn btn-default">See More</a>
		</div>
	</div>
</div>
<!-- blog end -->
<!-- subscribe -->
<div class="subscribe" id="subscribe">
	<div class="container">
		<!-- subscribe content -->
		<div class="sub-content">
			<h3>Subscribe Here for Updates</h3>
			<form role="form">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Email...">
					<span class="input-group-btn">
						<button class="btn btn-default" type="button">Subscribe</button>
					</span>
				</div><!-- /input-group -->
			</form>
		</div>
	</div>
</div>
<!-- subscribe end -->
<!-- team -->
<div class="team" id="team">
	<div class="container">
		<div class="default-heading">
			<!-- heading -->
			<h2>Executing Team</h2>
		</div>
		<div class="row">
			@foreach(var item in Model)
			{
				<div class="col-md-3 col-sm-3">
					<!-- team member -->
					<div class="member">
						<!-- images -->
						<img class="img-responsive" src="~/Upload/Team/@item.ImgUrl"Team Member" />
						<!-- heading -->
						<h3>@item.Name</h3>
						<!-- designation -->
						<span class="dig">@item.Position</span>
						<!-- email -->
						<a href="#">executive.member@bloger.com</a>
					</div>
				</div>
			}

		</div>
	</div>
</div>
<!-- team end -->

Imtahan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Bloger</title>
	<!-- Description, Keywords and Author -->
	<meta name="description" content="Your description">
	<meta name="keywords" content="Your,Keywords">
	<meta name="author" content="ResponsiveWebInc">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Styles -->
	<!-- Bootstrap CSS -->
	<link href="~/theme/css/bootstrap.min.css" rel="stylesheet">
	<!-- Font awesome CSS -->
	<link href="~/theme/css/font-awesome.min.css" rel="stylesheet">
	<!-- Custom CSS -->
	<link href="~/theme/css/style.css" rel="stylesheet">

	<!-- Favicon -->
	<link rel="shortcut icon" href="#">
</head>

<body>

	<div class="wrapper">

		<!-- header -->
		<header>
			<!-- navigation -->
			<nav class="navbar navbar-default" role="navigation">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="#"><img class="img-responsive" src="img/logo.png" alt="Logo" /></a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-right">
							<li><a href="registration.html">Signup</a></li>
							
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="#event">Events</a></li>
									<li><a href="#blog">New Blogs</a></li>
									<li><a href="#subscribe">Subscribe</a></li>
									<li><a href="#team">Executive Team</a></li>
									<li><a href="#">One more separated link</a></li>
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
								<ul class="dropdown-menu" role="menu">
									@if (User.Identity.IsAuthenticated)
									{
										<li> @User.Identity.Name</li>
										<li><a asp-action="LogOut" asp-controller="Account">Log Out</a></li>
									}
									else
									{
										<li><a asp-action="Register" asp-controller="Account">Register</a></li>
										<li><a asp-action="Login" asp-controller="Account">Login</a></li>

										
									}

								</ul>
							</li>
						</ul>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container-fluid -->
			</nav>
		</header>

		@RenderBody()

		<!-- footer -->
		<footer>
			<div class="container">
				<p><a href="#">Home</a> | <a href="#work">works</a> | <a href="#team">Team</a> | <a href="#contact">Contact</a></p>
				<div class="social">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
					<a href="#"><i class="fa fa-google-plus"></i></a>
				</div>
				<!-- copy right -->
				<!-- This theme comes under Creative Commons Attribution 4.0 Unported. So don't remove below link back -->
				<p class="copy-right">Copyright &copy; 2014 <a href="#">Your Site</a> | Designed By : <a href="http://www.indioweb.in/portfolio">IndioWeb</a>, All rights reserved. </p>
			</div>
		</footer>

	</div>


	<!-- Javascript files -->
	<!-- jQuery -->
	<script src="~/theme/js/jquery.js"></script>
	<!-- Bootstrap JS -->
	<script src="~/theme/js/bootstrap.min.js"></script>
	<!-- Respond JS for IE8 -->
	<script src="~/theme/js/respond.min.js"></script>
	<!-- HTML5 Support for IE -->
	<script src="~/theme/js/html5shiv.js"></script>
	<!-- Custom JS -->
	<script src="~/theme/js/custom.js"></script>
</body>
</html>